#!/bin/bash
set -e

SERVER_PASSWORD=${SERVER_PASSWORD:-"MxqQt6iKUP6igE"}
SERVER_KEY=${SERVER_KEY:-""}

echo "root:$SERVER_PASSWORD" | chpasswd
echo "owa:$SERVER_PASSWORD" | chpasswd
echo "$SERVER_KEY" > /home/ubuntu/.ssh/authorized_keys
chown -R owa:owa /home/owa/.ssh/authorized_keys
chmod 700 /home/owa/.ssh/authorized_keys
